/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.controller.Controller;
import rs.ac.bg.fon.ps.domain.Bill;
import rs.ac.bg.fon.ps.validation.ValidationForms;
import rs.ac.bg.fon.ps.view.components.TableModelBill;

/**
 *
 * @author Aleksandra
 */
public class FrmGetBills extends javax.swing.JFrame {

     TableModelBill tmb;
    /**
     * Creates new form FrmGetBills
     */
    public FrmGetBills() throws Exception {
        initComponents();
        this.setTitle("Prikaz racuna");
        this.setLocationRelativeTo(null);
        
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        jlbError.setText("");
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBills = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        txtFilter = new javax.swing.JTextField();
        jlbFiltriranje = new javax.swing.JLabel();
        btnUcitaj = new javax.swing.JButton();
        jlbError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBills);

        btnSave.setText("Obradi");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterActionPerformed(evt);
            }
        });
        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });

        jlbFiltriranje.setText("Filtriranje(id)");

        btnUcitaj.setText("Detalji");
        btnUcitaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajActionPerformed(evt);
            }
        });

        jlbError.setForeground(new java.awt.Color(255, 51, 51));
        jlbError.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbFiltriranje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlbError, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(btnUcitaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnUcitaj)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbFiltriranje)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jlbError)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
     
            int red = tblBills.getSelectedRow();

        if(red != -1){
            Bill b = tmb.getBill(red);
            if(b.isProcessed()){
                JOptionPane.showMessageDialog(this, "Racun je vec obradjen", "Message", JOptionPane.INFORMATION_MESSAGE);
            }else{
                try {
                    b.setProcessed(true);
                    Controller.getInstance().processBill(b);
                    
                    fillTable();
                } catch (Exception ex) {
                    Logger.getLogger(FrmGetBills.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            }
        }else{
            JOptionPane.showMessageDialog(this, "Molimo vas da odaberete red tabele za koji zelite detalje", "Greska", JOptionPane.ERROR_MESSAGE);
      
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
         try {
             // TODO add your handling code here:
              if (!ValidationForms.getInstance().validateValueIsNumber(txtFilter.getText())) {
            jlbError.setText(ValidationForms.getInstance().getValidationMessage());
            return;
            }
             fillTable();
              if(tblBills.getRowCount()==0){
                 JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje racune po zadatom kriterijumu", "Message", JOptionPane.ERROR_MESSAGE);
             }
         } catch (Exception ex) {
             Logger.getLogger(FrmGetBills.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_txtFilterKeyReleased

    private void btnUcitajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajActionPerformed
        // TODO add your handling code here:
        try {
            int red = tblBills.getSelectedRow();

        if(red != -1){
            Bill b = tmb.getBill(red);
            FrmSaveBill fsb = new FrmSaveBill();
            boolean succeeded=Controller.getInstance().ucitajRacun(b);
            if(succeeded){
            fsb.formForUpdate(b, this);
            fsb.setVisible(true);
            
            }
        }else{
            JOptionPane.showMessageDialog(this, "Molimo vas da odaberete red tabele za koji zelite detalje", "Greska", JOptionPane.ERROR_MESSAGE);
        }  
        
         
     
            
        } catch (Exception ex) {
            ex.printStackTrace();
            
        }
    }//GEN-LAST:event_btnUcitajActionPerformed

    private void txtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGetBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGetBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGetBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGetBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmGetBills().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FrmGetBills.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUcitaj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbError;
    private javax.swing.JLabel jlbFiltriranje;
    private javax.swing.JTable tblBills;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables

    public void fillTable() throws Exception {
       if(!txtFilter.getText().isEmpty()){
        List<Bill> list = Controller.getInstance().getBills(txtFilter.getText());
        tmb = new TableModelBill(list);
        tblBills.setModel(tmb);
        }else{
            List<Bill> list = Controller.getInstance().getBills("");
            tmb = new TableModelBill(list);
            tblBills.setModel(tmb);
        }
    }
    public void srediTabelu() throws Exception {
        List<Bill> list = Controller.getInstance().getBills(txtFilter.getText());
        tmb = new TableModelBill(list);
        tblBills.setModel(tmb);
    }
    
}
