/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.controller.Controller;

/**
 *
 * @author Aleksandra
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Glavna forma");
        jlbUser.setText("Dobrodošli "+Controller.getInstance().getCurrentUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProizvodi = new javax.swing.JMenu();
        jmiUnosProizvoda = new javax.swing.JMenuItem();
        jmiPrikazProizvoda = new javax.swing.JMenuItem();
        jMenuRacuni = new javax.swing.JMenu();
        jmiUnosRacuna = new javax.swing.JMenuItem();
        jmiPrikazRacuna = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbUser.setForeground(new java.awt.Color(153, 0, 153));
        jlbUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuProizvodi.setText("Proizvodi");

        jmiUnosProizvoda.setText("Unos proizvoda");
        jmiUnosProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosProizvodaActionPerformed(evt);
            }
        });
        jMenuProizvodi.add(jmiUnosProizvoda);

        jmiPrikazProizvoda.setText("Prikaz proizvoda");
        jmiPrikazProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazProizvodaActionPerformed(evt);
            }
        });
        jMenuProizvodi.add(jmiPrikazProizvoda);

        jMenuBar1.add(jMenuProizvodi);

        jMenuRacuni.setText("Racuni");

        jmiUnosRacuna.setText("Unos racuna");
        jmiUnosRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosRacunaActionPerformed(evt);
            }
        });
        jMenuRacuni.add(jmiUnosRacuna);

        jmiPrikazRacuna.setText("Prikaz racuna");
        jmiPrikazRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazRacunaActionPerformed(evt);
            }
        });
        jMenuRacuni.add(jmiPrikazRacuna);

        jMenuBar1.add(jMenuRacuni);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jlbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jlbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosProizvodaActionPerformed
        // TODO add your handling code here:
        new FrmSaveProduct().setVisible(true);
    }//GEN-LAST:event_jmiUnosProizvodaActionPerformed

    private void jmiPrikazProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazProizvodaActionPerformed
        // TODO add your handling code here:
        new FrmGetProducts().setVisible(true);
    }//GEN-LAST:event_jmiPrikazProizvodaActionPerformed

    private void jmiUnosRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosRacunaActionPerformed
        // TODO add your handling code here:
        new FrmSaveBill().setVisible(true);
    }//GEN-LAST:event_jmiUnosRacunaActionPerformed

    private void jmiPrikazRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazRacunaActionPerformed
        try {
            // TODO add your handling code here:
            new FrmGetBills().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiPrikazRacunaActionPerformed
 private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
      
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuProizvodi;
    private javax.swing.JMenu jMenuRacuni;
    private javax.swing.JLabel jlbUser;
    private javax.swing.JMenuItem jmiPrikazProizvoda;
    private javax.swing.JMenuItem jmiPrikazRacuna;
    private javax.swing.JMenuItem jmiUnosProizvoda;
    private javax.swing.JMenuItem jmiUnosRacuna;
    // End of variables declaration//GEN-END:variables
}
