/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.controller.Controller;
import rs.ac.bg.fon.ps.domain.Bill;
import rs.ac.bg.fon.ps.domain.BillItem;
import rs.ac.bg.fon.ps.domain.User;
import rs.ac.bg.fon.ps.view.components.TableModelBillItem;

/**
 *
 * @author Aleksandra
 */
public class FrmSaveBill extends javax.swing.JFrame {
    
    Bill b = null;
    TableModelBillItem tmbi;
    SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
    int row;
    FrmGetBills fgb;
     
    
   
    /**
     * Creates new form FrmSaveBill
     */
    public FrmSaveBill() {
       
        initComponents();
        this.setTitle("Unos racuna");
        this.setLocationRelativeTo(null);
        
        
        prepareView();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbDateOfIssue = new javax.swing.JLabel();
        jlbDate = new javax.swing.JLabel();
        jlbUser = new javax.swing.JLabel();
        jlbZaposleni = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        btnEditItem = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jlbIznos = new javax.swing.JLabel();
        jlbIznos1 = new javax.swing.JLabel();
        jlbUser2 = new javax.swing.JLabel();
        jlbZaposleni1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Racun"));

        jlbDateOfIssue.setText("Datum izdavanja:");

        jlbDate.setText("Date");

        jlbUser.setText("Korisnik");

        btnAddItem.setText("Dodaj stavku");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnEditItem.setText("Izmeni stavku");
        btnEditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditItemActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Obrisi stavku");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblItems);

        btnSave.setText("Sacuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Izmeni");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCancel.setText("Obrisi");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnClose.setText("Izadji");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jlbZaposleni1.setText("User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbDateOfIssue)
                            .addComponent(jlbUser))
                        .addGap(31, 31, 31)
                        .addComponent(jlbUser2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbZaposleni1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbIznos)
                            .addComponent(jlbIznos1))
                        .addGap(102, 102, 102))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(btnEditItem, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(64, 64, 64)
                                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(65, 65, 65)
                                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 46, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDateOfIssue)
                    .addComponent(jlbDate)
                    .addComponent(jlbIznos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbUser)
                    .addComponent(jlbZaposleni)
                    .addComponent(jlbIznos1)
                    .addComponent(jlbUser2)
                    .addComponent(jlbZaposleni1))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnEditItem)
                    .addComponent(btnDeleteItem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        try {
            FrmSaveBillItem fsbi = new FrmSaveBillItem();
            fsbi.setMtp(tmbi);
            fsbi.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnEditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditItemActionPerformed
        // TODO add your handling code here:
        row = tblItems.getSelectedRow();
        if(row != -1){
            try {
                BillItem bi= tmbi.getBillItem(row);
                FrmSaveBillItem fsbi = new FrmSaveBillItem();
                fsbi.fillForm(bi,row);
                fsbi.setMtp(tmbi);
                fsbi.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FrmSaveBill.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Niste izabrali red");
        }
        
    }//GEN-LAST:event_btnEditItemActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        double ukupanIznos = 0;

        ArrayList<BillItem> list = tmbi.getBillItemList();
        
        if(list.isEmpty()){
            JOptionPane.showMessageDialog(this, "Racun mora imati barem jednu stavku da bi se sacuvao!");
            return;
        }
        
        for(BillItem bi : list){
            ukupanIznos+=bi.getPrice().doubleValue();
        }
            
        User u = Controller.getInstance().getCurrentUser();

        Bill b1 = new Bill(-1l, new Date(),new BigDecimal( ukupanIznos), false, u, list);
        int response = JOptionPane.showConfirmDialog(this, "Ukupan iznos ovoj racuna je: " + ukupanIznos +"\nDa li ste sigurni da želite da ga sačuvate?","Čuvanje racuna", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.OK_OPTION) {

            try {
                Controller.getInstance().addBill(b1);
                
                cleanForm();
                dispose();
                new FrmGetBills().setVisible(true);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            
        }
        
    
       
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
        int row1 = tblItems.getSelectedRow();
        if(row1 != -1){
            
            tmbi.delete(row1);
            
        }else{
            JOptionPane.showMessageDialog(this, "Niste izabrali red");
        }
       
         
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try{
            String date=jlbDate.getText();
            String user=jlbUser.getText();
            double ukupanIznos = 0;

        ArrayList<BillItem> list = tmbi.getAllBillItems();
        ArrayList<BillItem> bezObrisanih=tmbi.getBillItemList();
        if(list.isEmpty()){
            JOptionPane.showMessageDialog(this, "Racun mora imati barem jednu stavku da bi se sacuvao!");
            return;
        }
        for(BillItem bi : bezObrisanih){
            ukupanIznos+=bi.getPrice().doubleValue();
        }
      
        User u = Controller.getInstance().getCurrentUser();
;
        Bill b1 = new Bill(b.getBillID(), b.getDate(),new BigDecimal( ukupanIznos), b.isProcessed(), u, list);
        for(BillItem b2:b1.getItems()){
            b2.setBill(b1);
        }
        if(b1.isProcessed()){
                JOptionPane.showMessageDialog(this, "Ne možete menjati racune koji su vec isporuceni","Greska",JOptionPane.ERROR_MESSAGE);
                return;
            }
         int response = JOptionPane.showConfirmDialog(this, "Ukupan iznos ovoj racuna je: " + ukupanIznos +"\nDa li ste sigurni da želite da ga sačuvate?", "Čuvanje racuna", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.OK_OPTION) {

            try {
                Controller.getInstance().updateBill(b1);
                
            } catch (Exception ex) {
                
                ex.printStackTrace();
            }
            
        }
        
       cleanForm();
       fgb.srediTabelu();
       dispose();
       fgb.setVisible(true);
        }catch(Exception ex){
            ex.printStackTrace();
           
        }
      
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
       
        if(b.isProcessed()){
                JOptionPane.showMessageDialog(this, "Ne možete brisati racune koji su vec isporuceni","Greska",JOptionPane.ERROR_MESSAGE);
                return;
            }
        int response = JOptionPane.showConfirmDialog(this, "Da li sigurno zelite da obrisete ovaj racun? Njegovo brisanje ce takodje obrisati sve njegove stavke.", "Brisanje racuna", JOptionPane.YES_NO_OPTION);
         if (response == JOptionPane.OK_OPTION) {
            try {
                Controller.getInstance().deleteBill(b);
                cleanForm();
                fgb.srediTabelu();
                dispose();
                fgb.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FrmSaveBill.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
         }else{
            JOptionPane.showMessageDialog(this, "Molimo vas da odaberete racun iz tabele koji zelite da obrisete.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
         
       
            
            

    }//GEN-LAST:event_btnCancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSaveBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSaveBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSaveBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSaveBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSaveBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditItem;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbDate;
    private javax.swing.JLabel jlbDateOfIssue;
    private javax.swing.JLabel jlbIznos;
    private javax.swing.JLabel jlbIznos1;
    private javax.swing.JLabel jlbUser;
    private javax.swing.JLabel jlbUser2;
    private javax.swing.JLabel jlbZaposleni;
    private javax.swing.JLabel jlbZaposleni1;
    private javax.swing.JTable tblItems;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        
        Date danasnji = new Date();
        btnClose.setVisible(false);
        jlbDate.setText(sdf.format(danasnji));
        jlbZaposleni1.setText(Controller.getInstance().getCurrentUser()+"");
        btnEdit.setVisible(false);
        btnCancel.setVisible(false);
       
       fillTable();
    }

    private void fillTable() {
        ArrayList<BillItem> list = b==null ? new ArrayList<>() : b.getItems();
        tmbi = new TableModelBillItem(list);
        tblItems.setModel(tmbi);
    }
      void formForDetails(Bill b, FrmGetBills aThis) {
        btnSave.setVisible(false);
        btnAddItem.setVisible(true);
        btnEditItem.setVisible(true);
        btnDeleteItem.setVisible(true);
        btnEdit.setVisible(true);
        btnCancel.setVisible(true);
        btnClose.setVisible(true);
        jlbIznos.setText("Ukupni iznos:");
        jlbIznos1.setText(b.getAmount()+"");
        this.b=b;
        this.fgb=fgb;
        if(b!=null)
            tmbi.setBillItemList(b.getItems());
        
        setTitle("Detalji o racunu");
    }
      private void cleanForm() {
         jlbDate.setText("");
        jlbUser2.setText("");
        jlbIznos1.setText("");
    }
   
    void formForUpdate(Bill bill, FrmGetBills fgb) {
        btnSave.setVisible(false);
        btnAddItem.setVisible(true);
        btnEditItem.setVisible(true);
        btnDeleteItem.setVisible(true);
        btnEdit.setVisible(true);
        btnCancel.setVisible(true);
        btnClose.setVisible(true);
        this.b=bill;
        this.fgb=fgb;
        if(b!=null)
            tmbi.setBillItemList(b.getItems());
        
        setTitle("Detalji o racunu");
    }
    
}

