/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.communication.Response;
import rs.ac.bg.fon.ps.controller.Controller;
import rs.ac.bg.fon.ps.domain.Distributor;
import rs.ac.bg.fon.ps.domain.Product;
import rs.ac.bg.fon.ps.validation.ValidationForms;


/**
 *
 * @author Aleksandra
 */
public class FrmSaveProduct extends javax.swing.JFrame {

    Product p;
    FrmGetProducts fgp;
  
    /**
     * Creates new form FrmSaveProduct
     */
    public FrmSaveProduct() {
        initComponents();
        try {
            this.setTitle("Unos proizvoda");
            this.setLocationRelativeTo(null);
          
            setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
            prepareView();
            
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error in view initialization: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jlbName = new javax.swing.JLabel();
        jlbPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jlbDescription = new javax.swing.JLabel();
        jlbDistributor = new javax.swing.JLabel();
        jcbDistributor = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDescription = new javax.swing.JTextArea();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jlbError = new javax.swing.JLabel();
        jlbError2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Proizvod"));

        jlbName.setText("Naziv:");

        jlbPrice.setText("Cena:");

        jlbDescription.setText("Opis:");

        jlbDistributor.setText("Distributer");

        jcbDistributor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSave.setText("Sacuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jtaDescription.setColumns(20);
        jtaDescription.setRows(5);
        jScrollPane2.setViewportView(jtaDescription);

        btnUpdate.setText("Izmeni");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Obrisi");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jlbError2.setForeground(new java.awt.Color(255, 0, 0));
        jlbError2.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbError2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbPrice)
                                    .addComponent(jlbName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbDistributor)
                                    .addComponent(jlbDescription))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                                    .addComponent(txtName)
                                    .addComponent(jcbDistributor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbDescription)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDistributor))
                .addGap(18, 18, 18)
                .addComponent(jlbError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbError2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
            // TODO add your handling code here:
            jlbError2.setText("");
            if (!ValidationForms.getInstance().validateEmpty(txtName, txtPrice)) {
            jlbError2.setText(ValidationForms.getInstance().getValidationMessage());
            return;
            }
            
            if (!ValidationForms.getInstance().validateEmpty1(jtaDescription)) {
            jlbError2.setText(ValidationForms.getInstance().getValidationMessage());
            return;
            }
             if (!ValidationForms.getInstance().validateValueIsNumber(txtPrice.getText())) {
            jlbError2.setText(ValidationForms.getInstance().getValidationMessage());
            return;
            }
         
             
          
       
        try {
            Product product=new Product();
            product.setName(txtName.getText().trim());
            product.setDescription(jtaDescription.getText().trim());
            String itemPrice=txtPrice.getText().trim();
            double price = Double.parseDouble(itemPrice);
            
            if(price <0){
                JOptionPane.showMessageDialog(this, "Cena mora biti pozitivan broj");
                return;
            }
            product.setPrice(new BigDecimal(itemPrice));
            
            product.setDistributor((Distributor) jcbDistributor.getSelectedItem());
            Controller.getInstance().addProduct(product);
            cleanForm();

        } catch (Exception ex) {
            ex.printStackTrace();
           JOptionPane.showMessageDialog(this, "Error: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
     
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
  
        jlbError2.setText("");
        if (!ValidationForms.getInstance().validateEmpty(txtName, txtPrice)) {
            jlbError2.setText(ValidationForms.getInstance().getValidationMessage());
            return;
        }
        
        if (!ValidationForms.getInstance().validateEmpty1(jtaDescription)) {
            jlbError2.setText(ValidationForms.getInstance().getValidationMessage());
            return;
        }
         if (!ValidationForms.getInstance().validateValueIsNumber(txtPrice.getText())) {
            jlbError2.setText(ValidationForms.getInstance().getValidationMessage());
            return;
            }
       
        
        
        String name = txtName.getText();
        String price = txtPrice.getText();
        String description = jtaDescription.getText();
      
        try{
     
        double price1 = Double.parseDouble(price);
        if(price1<0){
                JOptionPane.showMessageDialog(this, "Cena mora biti pozitivan broj");
                return;
            }
        
        Distributor d = (Distributor) jcbDistributor.getSelectedItem();
        
        Product p1=new Product(p.getId(),name,new BigDecimal(price),description,d);
      
        
       Controller.getInstance().updateProduct(p1);
     
       cleanForm();
       fgp.prepareView();
       dispose();
       fgp.setVisible(true);
        }catch(Exception ex){
            ex.printStackTrace();
             JOptionPane.showMessageDialog(this, "Error: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Da li sigurno zelite da obrisete proizvod " + p.getName() + "?", "Brisanje ucesnika", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.OK_OPTION) {
            try {
                Controller.getInstance().deleteProduct(p);
               cleanForm();
               fgp.prepareView();
                dispose();
                fgp.setVisible(true);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
           
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSaveProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSaveProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSaveProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSaveProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSaveProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcbDistributor;
    private javax.swing.JLabel jlbDescription;
    private javax.swing.JLabel jlbDistributor;
    private javax.swing.JLabel jlbError;
    private javax.swing.JLabel jlbError2;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbPrice;
    private javax.swing.JTextArea jtaDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
        jlbError2.setText("");
        btnDelete.setVisible(false);
        btnUpdate.setVisible(false);
        fillCmbDistributer();
    }

    private void fillCmbDistributer() throws Exception {
        jcbDistributor.removeAllItems();
        List<Distributor> distributors = Controller.getInstance().getAllDistributors();
        for (Distributor distributor : distributors ) {
            jcbDistributor.addItem(distributor);
        }
    }

    void fillFormDetails(Product p, FrmGetProducts fgp) {
        btnUpdate.setVisible(true);
        btnDelete.setVisible(true);
        btnSave.setVisible(false);
        this.p = p;
        this.fgp = fgp;
       txtName.setText(p.getName());
        jtaDescription.setText(p.getDescription());
        txtPrice.setText(p.getPrice()+"");
        jcbDistributor.setSelectedItem(p.getDistributor());
        txtName.setEditable(false);
        jcbDistributor.setEnabled(false);
        setTitle("Detalji o proizvodu");
    }

    private void cleanForm() {
        txtName.setText("");
        jtaDescription.setText("");
        txtPrice.setText("");
    }
}


